PA5: Hash.h ParallelProbingHash.h ProbingHash.h ChainingHash.h PerformanceTime.h Main.cpp PerformanceTime.cpp
	g++ -fopenmp -g -Wall -std=c++11 Main.cpp PerformanceTime.cpp -o PA5

clean:
	clear
	rm *.o *.gch PA5